---
title: "Cytokines with families annotation"
author: |
 | Juliana Beker Godoy, MSc
 | Graduate Program in Bioinformatics
 | Professional and Technological Education Sector
 | Federal University of Parana (UFPR)
 | Curitiba, Brazil
date: "`r Sys.Date()`"
output:
 rmarkdown::html_document:
   theme: cerulean
   highlight: haddock
   code_folding: hide
   toc: true
   toc_float: true
   smooth_scroll: true
   number_sections: false
   self_contained: true
---


```{r, clean, warning=FALSE, echo=FALSE, results='hide'}
#This command clean all variables. BE CAREFULL!!! 
rm(list = setdiff(ls(), lsf.str()))
```

```{r HelperFunctions, echo=FALSE, results='hide', warning=FALSE}
# Function to create useful tables
createDT <- function(DF, caption="", scrollY=500){
  data <- DT::datatable(DF, caption=caption,
   extensions =  'Buttons',
   options = list( dom = 'Bfrtip', 
                    buttons = c('copy', 'csv', 'excel', 'pdf', 'print'), 
                    scrollY = scrollY, scrollX=T, scrollCollapse = T, paging = F,  
                    columnDefs = list(list(className = 'dt-center', targets = "_all"))
    )
   ) 
   return(data)
}
```

```{r packages, warning=FALSE, echo=FALSE, message=FALSE}
library(tidyverse)
library(ggplot2)
library(readxl)
library(openxlsx)
```

```{r set_dir, echo=FALSE} 
work_dir = "C:/Users/beker/OneDrive/Documentos/Mestrado/GitHub/Cytokines/list_cytokines/T023/"
```

# Cytokines


This list of cytokines was constructed based on the supplementary material from [Cui et al. Nature, 2020](https://www.nature.com/articles/s41586-023-06816-9) e [Santoso Nucleic Acids Research et al., 2020](https://academic.oup.com/nar/article/48/21/12055/5976935?login=false).

```{r gene_list, warning=FALSE, message=FALSE}
# upload gene list
file_path <- "C:/Users/beker/OneDrive/Documentos/Mestrado/GitHub/Cytokines/list_cytokines/T023/list_cytokines_T023.xlsx"
cytokines <- read_excel(file_path)
```

```{r update_gene_family, warning=FALSE, message=FALSE}
# Reducing cytokine families
cytokines <- cytokines %>%
  mutate(family = case_when(
    family %in% c("IL-10", "IL-17", "IL-1", "Common γ chain/IL-13/TSLP", "IL-6/IL-12", "IL10", "IL32", "Common β chain") ~ "Interleukine",
    TRUE ~ family
  ))

createDT(cytokines)

# Saving excel
write.xlsx(cytokines, file = "C:/Users/beker/OneDrive/Documentos/Mestrado/GitHub/Cytokines/list_cytokines/T049/new_cytokines_families_T049.xlsx", row.names = FALSE)
```

```{r bar_plot, warning=FALSE, message=FALSE, fig.align='center', fig.width=8, fig.height=8, results='hide'}
# Frequency of genes 'family'
family_counts <- sort(table(cytokines$family), decreasing = TRUE)

# Barplot
bar_plot <- barplot(family_counts,
                    main = "Cytokine Genes Annotated by Family",
                    xlab = "Family",
                    ylab = "Number of genes",
                    col = "skyblue",
                    axisnames = FALSE,
                    ylim = c(0, max(family_counts) * 1.25))  # Increase the top margin by 10%) 

# Rotacionar as legendas do eixo x em 45 graus
text(x = bar_plot + 0.1, y = par("usr")[3] - 1.3, labels = names(family_counts), srt = 25, adj = c(1, 1.25), xpd = TRUE, cex = 1)

print(bar_plot)
```

# Session info

```{r}
sessionInfo()
```